Repository ISIS3510-2025-10-Grupo34/Dart-app, pull requests merged in 2025-04, with the labels that each got.

#55 Eventual conectivity strategies (Local cache) for leaving a review and sending a notification
  tutor_app/.env
  tutor_app/android/app/src/main/AndroidManifest.xml
  tutor_app/lib/controllers/connect_students_controller.dart
  tutor_app/lib/controllers/notification_controller.dart
  tutor_app/lib/controllers/write_review_controller.dart
  tutor_app/lib/main.dart
  tutor_app/lib/models/notification_model.dart
  tutor_app/lib/models/review_model.dart
  tutor_app/lib/services/local_cache_service.dart
  tutor_app/lib/services/location_service.dart
  tutor_app/lib/services/notication_cache_servicie.dart
  tutor_app/lib/services/review_service.dart
  tutor_app/lib/services/sync_service.dart
  tutor_app/lib/views/connect_students_screen.dart
  tutor_app/lib/views/notifications_view.dart
  tutor_app/lib/views/student_home_screen.dart
  tutor_app/lib/views/write_review_screen.dart
  tutor_app/macos/Flutter/GeneratedPluginRegistrant.swift
  tutor_app/pubspec.lock
  tutor_app/pubspec.yaml
  tutor_app/windows/flutter/generated_plugin_registrant.cc
  tutor_app/windows/flutter/generated_plugins.cmake
Labels: enhancement

#59 57 fix bottom overflowed in notificacions screen and save tutoring sessions to review
  tutor_app/lib/controllers/student_tutoring_sessions_controller.dart
  tutor_app/lib/models/tutoring_session_model.dart
  tutor_app/lib/services/sync_service.dart
  tutor_app/lib/views/connect_students_screen.dart
  tutor_app/lib/views/student_home_screen.dart
  tutor_app/lib/views/student_profile_screen.dart
Labels: bug, enhancement

#68 60 suscription and book feature
  tutor_app/.env
  tutor_app/lib/controllers/student_home_controller.dart
  tutor_app/lib/services/tutoring_session_service.dart
  tutor_app/lib/views/filter_modal.dart
  tutor_app/lib/views/student_home_screen.dart
Labels: feature
